name: Deploy Jekyll with Secrets
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ВСТАВЛЯЕМ ТВОЙ СКРИПТ ТУТ
      - name: Replace secret with Python
        env:
          MY_SECRET_VALUE: ${{ secrets.SECRET_CODE }}
        run: |
          python3 -c "
          import os
          path = 'script.js'
          with open(path, 'r', encoding='utf-8') as f:
              content = f.read()
          secret = os.environ['MY_SECRET_VALUE'].strip().strip('\'\"')
          new_content = content.replace('__SECRET_CODE__', secret)
          with open(path, 'w', encoding='utf-8') as f:
              f.write(new_content)
          "

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
