name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Запускать при пуше в main

permissions:
  contents: write # Разрешение на запись, чтобы обновить сайт

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace secret with Python
        env:
          MY_SECRET_VALUE: ${{ secrets.SECRET_CODE }}
        run: |
          python3 -c "
          import os
          path = 'script.js'
          with open(path, 'r', encoding='utf-8') as f:
              content = f.read()
          # Заменяем __SECRET_CODE__ на значение из секретов
          new_content = content.replace('__SECRET_CODE__', os.environ['MY_SECRET_VALUE'])
          with open(path, 'w', encoding='utf-8') as f:
              f.write(new_content)
          "

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Деплоим всё содержимое текущей папки
          branch: gh-pages # Ветка, из которой работает ваш сайт
